### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by wgarnes** [featurehub-io/featurehub-install#31]
I am trying to run the [featurehub/party-server ](https://hub.docker.com/r/featurehub/party-server) image on my computer for local development and testing.  However the chip in the computer is the Apple M1 Max (which uses the arm64 architecture).  Can you build a new image that is arm64 compatible?

**Comment by rvowles** [comment]
I made some progress on this, but events overtook me. We expect we will be able to get it out within the next week!

**Comment by wgarnes** [comment]
Looks like the new image `featurehub/party-server:1.5.7-RC-multi` works.  Thanks for the fix!
